branches:
    only:
        - production
before_script:
    - openssl aes-256-cbc -K $encrypted_34f53ba26646_key -iv $encrypted_34f53ba26646_iv -in .travis/deploy_key.enc -out .travis/deploy_key -d
script:
    - echo hi
after_success:
    - eval "$(ssh-agent -s)"
    - chmod 600 .travis/deploy_key
    - ssh-add .travis/deploy_key
    - echo -e "Host haroku.844196.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    - git remote add haroku dokku@haroku.844196.com:sample
    - git push haroku master
