branches:
    only:
        - production
env:
    global:
        - GIT_COMMITTER_NAME='Masaya Takeda'
        - GIT_COMMITTER_EMAIL=844196@gmail.com
        - GIT_AUTHOR_NAME='Masaya Takeda'
        - GIT_AUTHOR_EMAIL=844196@gmail.com
addons:
    ssh_known_hosts: haroku.844196.com
before_script:
    - openssl aes-256-cbc -K $encrypted_34f53ba26646_key -iv $encrypted_34f53ba26646_iv -in .travis/deploy_key.enc -out ~/.ssh/deploy_key -d
script:
    - echo hi
after_success:
    - eval "$(ssh-agent -s)"
    - chmod 600 ~/.ssh/deploy_key
    - ssh-add ~/.ssh/deploy_key
    - echo -e "Host haroku.844196.com\n\tStrictHostKeyChecking no\nIdentityFile ~/.ssh/deploy_key\n" >> ~/.ssh/config
    - git add --all
    - 'git commit -m "Generate Travis JOB $TRAVIS_JOB_NUMBER"'
    - git remote add haroku dokku@haroku.844196.com:sample
    - git push haroku master
